### ISSUE TITLE
Кодліст: fundingType

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#11]
| **code**         | **value**     |
|--------------|-----------|
| nonFinancial | In-kind   |
| financial    | Financial |

Якщо з якоїсь причини ми не можемо привʼязати кошти до певної категорії fundingType, слід позначати такі записи як Not specified, а не просто робити їх null записами. В такий спосіб буде простіше діагностувати, де, як і чому виникає проблема.

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
> Якщо з якоїсь причини ми не можемо привʼязати кошти до певної категорії fundingType, слід позначати такі записи як Not specified, а не просто робити їх null записами.

**Comment by andrzejbeletsky** [comment]
in progress
