### ISSUE TITLE
Monitoring sheet: Виправити посилання, котрі не працюють

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#13]
Частина посилань на аркуші Monitoring sheet не працюють і вказують на https://public-api-dev.dream.gov.ua/marketplace/public/dream/aggregations/ замість https://public-api-dev.dream.gov.ua/marketplace/public/dream/aggregations/{id}

Коди записів із ідентифікованими проблемами

140224-00D07ED6
140224-D79EEF27
140224-0E256CC7
140224-9560963E
140224-401EEF3F

Перелік може бути не вичерпний, оскільки записи були виявлені простим перебором - ручною перевіркою.

#8

**Comment by andrzejbeletsky** [comment]
Done.
Виправлено модель.

**Comment by ndrhzn** [comment]
@andrzejbeletsky помітив новий баг - ось тут частина посилань просто відсутня

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/4e956650-b22b-4875-a930-4e5938bd6816)

**Comment by andrzejbeletsky** [comment]
in progress.
якось зв'язано з неправильною обробкою "Ukrainian Government Priority"..

**Comment by andrzejbeletsky** [comment]
Знайшов причину.
Це через фільтр по року.
Виникає питання - таблиця має показники по різних роках. Яке має бути її поведінка при обраному фільтру по року?

**Comment by andrzejbeletsky** [comment]
Take a look.
https://qsdemo.rbcgrp.com/sense/app/9720c067-ce0a-4e54-9d21-45b7ace7ad00/sheet/3eefbab8-7358-4d20-afda-fc02aaeb77be/state/analysis
Виправив показники "Total need estimation", "Total commitment / Total amount of Agreement" - показують правильні загальні цифри і не реагують на вибір року в фільтрах.
На інші фільтри таблиця реагує.
