### ISSUE TITLE
UI: Прибрати фільтри зі зведених таблиць

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#14]
Один із запитів, що надійшов від Проєктного офісу - прибрати фільтри зі зведених таблиць, оскільки вони значною мірою дублюють вже наявні на панелі фільтрів.

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/37853797-286c-46c1-928c-f492642cd7c7)

Тут є кілька думок за те, щоб прибрати, і за те, щоб лишити. І, звісно, ми наразі навіть не знаємо, чи зведені таблиці у Qlik в принципі дозволяють таке робити.

**За те, щоб прибрати**

- У нас вже є панель фільтрів, дублювання фільтрів у таблиці лише забирає місце і не створює цінності

**За те, щоб лишити**

- Ці фільтри дозволяють міняти порядок розрізів, і таким чином можна побачити ієрархію / агрегацію в різних варіаціях (але для користуачів це може бути геть неочевидно, особливо якщо це не дуже досвідчені користувачі)

- Ці фільтри підказують, що саме користувачі бачать на екрані, оскільки без них додаткові рівні, котрі розкриваються по кліку на плюсик, можуть бути не дуже зрозумілими

Що ви про це думаєте? Чи можливо це технічно в принципі (чи є сенс обговорювати імплементацію загалом)? Або чи можливо залишити підписи, але прибрати з них функціонал фільтрування даних?

**Comment by andrzejbeletsky** [comment]
Прибрати можна. Але зовсім.
Втрачаємо те, що правильно перелічене вище.
