### ISSUE TITLE
Data: Перевірити та виправити процес парсингу даних

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#15]
Все ще намагаюся розібратися із записами, для яких у нас можуть бути відсутні певні сутності в даних, використовуючи Monitoring sheet.

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/c38bbb4f-4d05-408c-a745-f150b8075b70)

Звернув увагу на перший у цьому списку NeedID - 140224-5305B6FE. 

У таблиці у нас зокрема відсутні значення для Funding provider, Funding form, Funding type.

Якщо [подивитися на дані АРІ](https://public-api-dev.dream.gov.ua/marketplace/public/dream/aggregations/l2z38lt8-e7x8-4c38-a475-7jie5s3zc3ib), тоді там вся ця інформація наче як є.

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/d15ee7c1-c4f9-4a4c-b347-02312c0d859c)

Чому так відбувається? І як це можна виправити?

**Comment by andrzejbeletsky** [comment]
Done.
Змінено модель.
