### ISSUE TITLE
Bug: Декілька значень у стовпчику Ukrainian Government Priority

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#17]
@andrzejbeletsky, звернув увагу, що у таблиці Monitoring sheet у стовпчику Ukrainian Government Priority тепера можливі випадки, коли в одній комірці буде два значення, одне з котрих - Not specified. 

Не дуже розумію, чому це стається, і як такі записи інтерпретувати?

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/149b6fb1-9938-4f74-8cd9-cc8041962399)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
Виправлено
Not specified - тільки коли немає іншого значення
