### ISSUE TITLE
Bug: Not specified показується навіть у тих випадках, коли у цьому немає потреби

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#18]
В результаті останніх змін у нас виникла ситуація, коли категорія Not specified зʼявляється у візуалізаціях навіть тоді, коли це не має жодного значення

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/ef79d24f-0a97-4782-a42d-bd8af63e081d)

Скажімо, у цьому прикладі категорія Not specified не має даних - Commitment і Available мають значення 0. Таким чином, категорія Not specified, котра від самого початку була покликана допомогти виявити проблеми у даних, тепера просто створює такі повністю порожні стовпчики, котрі не мають жодної цінності для користувачів.

Ця проблема спостерігається на аркуші Needs funding sources для всіх розрізів - Donor type, Funding provider, Funding type, Funding form.

Можливе рішення - відфільтровувати значення перед тим, як показувати їх. Тільки тут треба чітко визначитися із тим, за яким правилом ми фільтруємо, аби не захопити нічого цінного.

**Comment by andrzejbeletsky** [comment]
Відключив показ нульових значень

**Comment by ndrhzn** [comment]
От мені здається, що із задачею "не захопити нічого цінного" ми тут не впорались. Ось, що я бачу наразі

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/bca37b9a-6741-4d01-9345-985ec2c17fe0)

Очікування такі, що мають показуватися всі категорії, окрім Not specified, за умови, що для Not specified обидва значення (commitment & available) дорівнюють нулю.

**Comment by andrzejbeletsky** [comment]
Тепер бачу іншу проблему з булет-чартом.
Фактично, він оперує з першою мірою, і відносно неї відображає 2-гу (у нас це target). 
І відключення показу нулів стосується тільки головної першої міри, і тоді зовсім нічого немає на графіку, коли перша міра =0.

**Comment by andrzejbeletsky** [comment]
перероблюю..
