### ISSUE TITLE
Дешборд: Видалити зайві аркуші

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#2]
Отже, ми нарешті узгодили, які способи візуалізації ми беремо в продуктив, а які відкидаємо. 

[**Needs general information**](https://qsdemo.rbcgrp.com/http/sense/app/9720c067-ce0a-4e54-9d21-45b7ace7ad00/sheet/fa17a26a-9874-465f-adba-6e8cbc60e98b/state/analysis)

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/d6d925fe-0246-4921-ac34-869a87eb9af6)

[**Needs fulfilment rate (Auto)**](https://qsdemo.rbcgrp.com/http/sense/app/9720c067-ce0a-4e54-9d21-45b7ace7ad00/sheet/0a6d534b-b6ac-4dd2-883b-886b42ca5f46/state/analysis) - тут треба прибрати Auto з назви аркуша

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/458376c6-9624-4128-8cc8-22e52012dfe3)

[**Needs funding sources (Auto)**](https://qsdemo.rbcgrp.com/http/sense/app/9720c067-ce0a-4e54-9d21-45b7ace7ad00/sheet/51eb349a-e5b9-4b80-a1a3-d8e8bd34b89e/state/analysis) - тут треба прибрати Auto з назви аркуша

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/06f6db21-2e93-4fc0-9e9a-fb34d70f3e41)

[**Monitoring sheet**](https://qsdemo.rbcgrp.com/http/sense/app/9720c067-ce0a-4e54-9d21-45b7ace7ad00/sheet/3eefbab8-7358-4d20-afda-fc02aaeb77be/state/analysis)

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/94af2df9-2164-442a-a6df-3d0ebcc573f1)

**Comment by andrzejbeletsky** [comment]
Done
