### ISSUE TITLE
Charts: Додати до bullet charts підпис другого числового значення

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#20]
Від самого початку в нас був запит від Проєктного офісу на те, щоб на  bullet chart показувати числові підписи і для target value, і для fact value. Однак ми не могли цього зробити через обмеження самого шаблону bullet chart. Водночас ми говорили про те, що є можливість спробувати застосувати новий функціонал Qlik - [layout container](https://community.qlik.com/t5/Support-Updates/Techspert-Talks-Visualization-Day/ba-p/2122007) для цієї задачі. 

Ймовірно перша задача у цьому напрямку - спробувати зробити один графік із використанням layout container та додаванням двох числових записів, аби зрозуміти можливості та обмеження.

**Comment by andrzejbeletsky** [comment]
Найкращий варіант виходить з 2-ма стовпчиками. Візуально, порівняно з булетом, не так і зменшується кількість відображеної інформації.
https://qsdemo.rbcgrp.com/sense/app/9720c067-ce0a-4e54-9d21-45b7ace7ad00/sheet/a90501f3-4cab-45d0-837f-3201540f127a/state/analysis
Можливо, під графіки відвести більше місця, а таблицю винести окремо (в контейнер на цьому аркуші)?

**Comment by ndrhzn** [comment]
Зрозумів, дякую. В такому разі поки нічого більше робити не треба. Варіант із двома стовпчиками я пропонував Дмитрові серед опцій, але він надав перевагу bullet chart. Тому поки зафіксуємось на цьому варіанті, а якщо будуть якісь додаткові ввідні від користувачів, будемо вже обробляти їх
