### ISSUE TITLE
Кодліст: Funding provider

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#3]
Для змінної Funding provider нам потрібно буде додати кодліст, аби відображати не коди, а зрозумілі і зручні для читання назви. З'ясовую, чи кодліст вже наявний і готовий до роботи.

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/c4063ab7-9dcb-407c-b814-4abdeaf9c286)

**Comment by ndrhzn** [comment]
З оновленням даних тут змінилися можливі значення змінної budget/finance/financingParty/id, але задача підтягування кодліста лишилася.

Наразі у нас є декілька категорій funding providers і декілька задач. Задокументую їх тут окремо

Якщо budget/finance/financeCategory="bilateralSupport", тоді у budget/finance/financingParty/id ми маємо дволітерні коди країн, котрі потрібно трансформувати у людиночитані назви країн, використовуючи той самий класифікатор, що ми використовуємо для основного модулю.

**Comment by ndrhzn** [comment]
Також у нас є декілька кодів, котрі поки що не розшифровані (вони є в АРІ, але я не бачу їх на графіку, що, очевидно, витікає з проблеми поєднання даних). Звернув увагу, що деякі з цих кодів у нас не розшифровані нормально у основному модулі, оновлю кодліст і там.

| code            | value                                                            |
|-----------------|------------------------------------------------------------------|
| otherCommon     | Other, general fund                                              |
| united24        | United24                                                         |
| liquidationFund | Fund for the Liquidation of the Consequences of Armed Aggression |

**Comment by andrzejbeletsky** [comment]
Для країн зробив.
Як щодо інших? Якщо взяти код-лист з основного модулю (https://docs.google.com/spreadsheets/d/1efMobfMAItctWak9UmULWInX02GH5TeKXsWXFHkG5Ww/edit?pli=1#gid=2050112638), там багато не переведено на англійську коректно.
Залишити поки скорочення як є?

**Comment by ndrhzn** [comment]
Поки лишаємо скорочення як є. Але варто зробити так, аби для випадків, коли fundingProvider не визначено, ми мали не null записи, позначені "-", а записи, позначені Not specified.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Після виправлення моделі даних у нас зʼявилися нові категорії у Funding Provider

![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/e2af5d86-c7fd-46ad-9ef7-b8a9d5f0ae06)

Частково кодліст був описаний [вище у коментарях](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/issues/3#issuecomment-1956311525).

Для тих випадків, коли у нас код є кодом ЄДРПОУ у форматі "UA-EDR-40075815", ймовірно, можна взяти financingParty/name

Ось те, що у нас наразі виходить з фактичних даних. Всі записи українською, однак на цьому етапі це може бути краще, ніж просто коди

| **id**          | **name**                                 |
|-----------------|------------------------------------------|
| UA-EDR-40075815 | АТ УКРАЇНСЬКА ЗАЛІЗНИЦЯ                  |
| UA-EDR-42644659 | ПАТ ЕКСПОРТНО-КРЕДИТНЕ АГЕНТСТВО         |
| UA-EDR-40516827 | ТОВ ФОНД ЕНЕРГОЕФЕКТИВНОСТІ              |
| UA-EDR-00100227 | ПАТ НЕК УКРЕНЕРГО                        |
| UA-EDR-38727770 | ДП АДМІНІСТРАЦІЯ МОРСЬКИХ ПОРТІВ УКРАЇНИ |
| UA-EDR-20588716 | ПАТ УКРГІДРОЕНЕРГО                       |

**Comment by andrzejbeletsky** [comment]
in progress
