### ISSUE TITLE
Дані / фільтри: Funding provider vs Donor Title 

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#5]
Зараз у нас у фільтрах є дві сутності, котрі дуже схожі за змістом. Потрібно прояснити, чи це одна сутність, чи дві окремі. Якщо одна, тоді потрібно залишити тільки один фільтр.

**Comment by ndrhzn** [comment]
![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/cb29b7cb-72c4-40f6-a616-35bd04dde107)

@andrzejbeletsky  а звідки зара тягнуться Funding Provider & Donor Title - це одне й те саме чи це дві різні речі?

**Comment by andrzejbeletsky** [comment]
Так, це одне й те саме.
Залишив тільки Funding Provider.
