### ISSUE TITLE
Charts: Виправити відображення даних для випадків, коли відсутні дані щодо available & disbursed

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#6]
![image](https://github.com/open-contracting/bi.dream.gov.ua-mdcp/assets/13032566/a98434f2-2bf0-419d-bbc8-0945eeff0ee2)

У цьому прикладі ми бачимо, що в секції Available vs Disbursed відмальовується стовпчик від 0 до -1, що очевидно некоректно. Ймовірно в таких випадках не варто показувати взагалі нічого, хіба що ось те службове повідомлення про те, що Selection generated no data.

Наразі помилка відтворюється, коли обрано 2024 чи 2024 рік, оскільки для цих років ми не маємо даних для Available & Disbursed.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
Done
