### ISSUE TITLE
UI: Уніфікувати порядок / пріоритет фільтрів на всіх аркушах

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua-mdcp#9]
Перша задача - виписати бажаний порядок, в якому мають йти фільтри

**Comment by ndrhzn** [comment]
Поточний перелік та порядок фільтрів на всіх аркушах

| **Needs general information** | **Needs fullfilment rate**    | **Needs funding sources**     | **Monitoring sheet**          |
|-------------------------------|-------------------------------|-------------------------------|-------------------------------|
| Ukrainian Government Priority | Ukrainian Government Priority | RDNA Sector                   | NeedID                        |
| RDNA Sector                   | RDNA Sector                   | RDNA Subsector                | Need name                     |
| RDNA Subsector                | RDNA Subsector                | RDNA Component                | RDNA Sector                   |
| RDNA Component                | RDNA Component                | Ukrainian Government Priority | RDNA Subsector                |
| Donor type                    | Donor type                    | Year                          | RDNA Component                |
| Funding provider              | Funding provider              |                               | Ukrainian Government Priority |
| Funding type                  | Funding type                  |                               | Agreement name                |
| Funding form                  | Funding form                  |                               | Funding form                  |
| Year                          | Year                          |                               | Funding provider              |
| NeedID                        | NeedID                        |                               | Donor type                    |
| Need name                     | Need name                     |                               | Year                          |
| Agreement name                | Agreement name                |                               |                               |

**Comment by ndrhzn** [comment]
Видається, що на першому і другому аркуша можна лишити все, як є.

На третьому аркуші є сенс змінити порядок фільтрів таким чином, аби Ukrainian Government Priority був на першому місці (як у перших двох випадках). У цьому випадку немає сенсу додавати нових фільтрів, оскільки частина тих розрізів, що могли би бути фільтрами, у нас винесена у спадаючий список, від якого залежить стовпчиковий графік.

На четвертому аркуші є сенс зробити такий самий набір порядок фільтрів, як на першому і другому.

**Comment by andrzejbeletsky** [comment]
оновив фільтри
